platform :ios, '8.1'

use_frameworks!

target 'AnAnOrderCarDriver' do

pod 'Alamofire'#网络请求

pod 'SwiftyJSON'#数据解析

pod 'NVActivityIndicatorView'#加载动画

pod 'DGElasticPullToRefresh'#下拉刷新

pod 'Log'#日志框架

end
