#source 'https://github.com/jiazifa/SSFormSwift.git'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/jiazifa/Specs.git'

platform :ios, '8.1'

inhibit_all_warnings!#不显示第三方库中的警告
use_frameworks!

target 'pandaMaMa' do
    
    pod 'Alamofire', '~> 4.4.0'#网络请求
    
    pod 'SwiftyJSON', '~> 3.1.4'#数据解析
    
    pod 'SnapKit', '~> 3.2.0'#自动布局
    
    pod 'NVActivityIndicatorView', '~> 3.6.1'#加载动画
    
    pod 'DGElasticPullToRefresh', '~> 1.1'#下拉刷新
    
    pod 'Kingfisher', '~> 3.6.2' #图片加载框架
    
    pod 'IQKeyboardManager', '~> 4.0.9' #, :inhibit_all_warnings => true表示允许此库显示警告信息
    
    #私有库内容
     pod 'SSKitSwift', '0.1.3'
end
